name: Deploy Full Stack App to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy project to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/${{ secrets.SERVER_USER }}/frontend/app"

    - name: Build project on server and deploy to Nginx
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /${{ secrets.SERVER_USER }}/frontend/app
          # yarn install --frozen-lockfile
          yarn build

          # Remove old build
          sudo rm -rf /var/www/frontend/*

          # Copy new build
          sudo cp -r build/* /var/www/frontend/

          echo "✅ Frontend deployed successfully!"
